export class Acl {
  static api = 'http://safety.iaa.ir/api/';
static Safety='Safety';
static SafetyOther='SafetyOther';
static SafetyOtherAdminDashboard='SafetyOtherAdminDashboard';
static SafetyQMS='SafetyQMS';
static SafetyQMSBasicInfo='SafetyQMSBasicInfo';
static SafetyQMSBasicInfoLocation='SafetyQMSBasicInfoLocation';
static SafetyQMSBasicInfoLocationSave='SafetyQMSBasicInfoLocationSave';
static SafetyQMSBasicInfoLocationFindAll='SafetyQMSBasicInfoLocationFindAll';
static SafetyQMSBasicInfoLocationDelete='SafetyQMSBasicInfoLocationDelete';
static SafetyQMSBasicInfoLocationFind='SafetyQMSBasicInfoLocationFind';
static SafetyQMSBasicInfoAuditee='SafetyQMSBasicInfoAuditee';
static SafetyQMSBasicInfoAuditeeSave='SafetyQMSBasicInfoAuditeeSave';
static SafetyQMSBasicInfoAuditeeFindAll='SafetyQMSBasicInfoAuditeeFindAll';
static SafetyQMSBasicInfoAuditeeDelete='SafetyQMSBasicInfoAuditeeDelete';
static SafetyQMSBasicInfoAuditeeFind='SafetyQMSBasicInfoAuditeeFind';
static SafetyQMSBasicInfoLocationFindWithRouteId='SafetyQMSBasicInfoLocationFindWithRouteId';
static SafetyQMSBasicInfoAuditeeFindWithRouteId='SafetyQMSBasicInfoAuditeeFindWithRouteId';
static SafetyQMSBasicInfoAuditor='SafetyQMSBasicInfoAuditor';
static SafetyQMSBasicInfoAuditorSave='SafetyQMSBasicInfoAuditorSave';
static SafetyQMSBasicInfoAuditorFindAll='SafetyQMSBasicInfoAuditorFindAll';
static SafetyQMSBasicInfoAuditorDelete='SafetyQMSBasicInfoAuditorDelete';
static SafetyQMSBasicInfoAuditorFind='SafetyQMSBasicInfoAuditorFind';
static SafetyQMSBasicInfoAuditorFindWithRouteId='SafetyQMSBasicInfoAuditorFindWithRouteId';
static SafetyQMSBasicInfoRootCause='SafetyQMSBasicInfoRootCause';
static SafetyQMSBasicInfoRootCauseSave='SafetyQMSBasicInfoRootCauseSave';
static SafetyQMSBasicInfoRootCauseFindAll='SafetyQMSBasicInfoRootCauseFindAll';
static SafetyQMSBasicInfoRootCauseDelete='SafetyQMSBasicInfoRootCauseDelete';
static SafetyQMSBasicInfoRootCauseDetail='SafetyQMSBasicInfoRootCauseDetail';
static SafetyQMSBasicInfoRootCauseDetailSave='SafetyQMSBasicInfoRootCauseDetailSave';
static SafetyQMSBasicInfoRootCauseDetailFindAll='SafetyQMSBasicInfoRootCauseDetailFindAll';
static SafetyQMSBasicInfoRootCauseDetailDelete='SafetyQMSBasicInfoRootCauseDetailDelete';
static SafetyQMSBasicInfoRootCauseDetailFindByRootCauseId='SafetyQMSBasicInfoRootCauseDetailFindByRootCauseId';
static SafetyQMSBasicInfoScope='SafetyQMSBasicInfoScope';
static SafetyQMSBasicInfoScopeSave='SafetyQMSBasicInfoScopeSave';
static SafetyQMSBasicInfoScopeFindAll='SafetyQMSBasicInfoScopeFindAll';
static SafetyQMSBasicInfoScopeDelete='SafetyQMSBasicInfoScopeDelete';
static SafetyQMSBasicInfoScopeFind='SafetyQMSBasicInfoScopeFind';
static SafetyQMSBasicInfoScopeFindWithRouteId='SafetyQMSBasicInfoScopeFindWithRouteId';
static SafetyQMSBasicInfoStatus='SafetyQMSBasicInfoStatus';
static SafetyQMSBasicInfoStatusFindAll='SafetyQMSBasicInfoStatusFindAll';
static SafetyQMSBasicInfoScopeDetails='SafetyQMSBasicInfoScopeDetails';
static SafetyQMSBasicInfoScopeDetailsSave='SafetyQMSBasicInfoScopeDetailsSave';
static SafetyQMSBasicInfoScopeDetailsFindAll='SafetyQMSBasicInfoScopeDetailsFindAll';
static SafetyQMSBasicInfoScopeDetailsDelete='SafetyQMSBasicInfoScopeDetailsDelete';
static SafetyQMSBasicInfoScopeDetailsFind='SafetyQMSBasicInfoScopeDetailsFind';
static SafetyQMSBasicInfoScopeDetailsFindByScope='SafetyQMSBasicInfoScopeDetailsFindByScope';
static SafetyQMSBasicInfoExternalFindingType='SafetyQMSBasicInfoExternalFindingType';
static SafetyQMSBasicInfoExternalFindingTypeSave='SafetyQMSBasicInfoExternalFindingTypeSave';
static SafetyQMSBasicInfoExternalFindingTypeFindAll='SafetyQMSBasicInfoExternalFindingTypeFindAll';
static SafetyQMSBasicInfoExternalFindingTypeDelete='SafetyQMSBasicInfoExternalFindingTypeDelete';
static SafetyQMSBasicInfoExternalFindingTypeFind='SafetyQMSBasicInfoExternalFindingTypeFind';
static SafetyQMSBasicInfoAuditType='SafetyQMSBasicInfoAuditType';
static SafetyQMSBasicInfoAuditTypeSave='SafetyQMSBasicInfoAuditTypeSave';
static SafetyQMSBasicInfoAuditTypeFindAll='SafetyQMSBasicInfoAuditTypeFindAll';
static SafetyQMSBasicInfoAuditTypeDelete='SafetyQMSBasicInfoAuditTypeDelete';
static SafetyQMSBasicInfoAuditTypeFind='SafetyQMSBasicInfoAuditTypeFind';
static SafetyQMSScheduler='SafetyQMSScheduler';
static SafetyQMSSchedulerScheduler='SafetyQMSSchedulerScheduler';
static SafetyQMSSchedulerSchedulerSave='SafetyQMSSchedulerSchedulerSave';
static SafetyQMSSchedulerSchedulerFindAll='SafetyQMSSchedulerSchedulerFindAll';
static SafetyQMSSchedulerSchedulerDelete='SafetyQMSSchedulerSchedulerDelete';
static SafetyQMSSchedulerSchedulerFind='SafetyQMSSchedulerSchedulerFind';
static SafetyQMSSchedulerSchedulerFindAllDashboard='SafetyQMSSchedulerSchedulerFindAllDashboard';
static SafetyQMSSchedulerSchedulerFindFullVersion='SafetyQMSSchedulerSchedulerFindFullVersion';
static SafetyQMSSchedulerSchedulerGetLatesVersionForReport='SafetyQMSSchedulerSchedulerGetLatesVersionForReport';
static SafetyQMSSchedulerSchedulerFindAllFindingForChart='SafetyQMSSchedulerSchedulerFindAllFindingForChart';
static SafetyQMSSchedulerSchedulerFindAllFindingForReport='SafetyQMSSchedulerSchedulerFindAllFindingForReport';
static SafetyQMSSchedulerSchedulerFindAllFinding='SafetyQMSSchedulerSchedulerFindAllFinding';
static SafetyQMSRisk='SafetyQMSRisk';
static SafetyQMSRiskSeverity='SafetyQMSRiskSeverity';
static SafetyQMSRiskSeveritySave='SafetyQMSRiskSeveritySave';
static SafetyQMSRiskSeverityFindAll='SafetyQMSRiskSeverityFindAll';
static SafetyQMSRiskSeverityDelete='SafetyQMSRiskSeverityDelete';
static SafetyQMSRiskProbability='SafetyQMSRiskProbability';
static SafetyQMSRiskProbabilitySave='SafetyQMSRiskProbabilitySave';
static SafetyQMSRiskProbabilityFindAll='SafetyQMSRiskProbabilityFindAll';
static SafetyQMSRiskProbabilityDelete='SafetyQMSRiskProbabilityDelete';
static SafetyQMSRiskRiskManagment='SafetyQMSRiskRiskManagment';
static SafetyQMSRiskRiskManagmentSave='SafetyQMSRiskRiskManagmentSave';
static SafetyQMSRiskRiskManagmentFindAll='SafetyQMSRiskRiskManagmentFindAll';
static SafetyQMSRiskRiskManagmentDelete='SafetyQMSRiskRiskManagmentDelete';
static SafetyQMSRiskRiskManagmentFindBySeverityProbability='SafetyQMSRiskRiskManagmentFindBySeverityProbability';
static SafetyQMSReport='SafetyQMSReport';
static SafetyQMSReportReport='SafetyQMSReportReport';
static SafetyQMSReportReportRampInspection='SafetyQMSReportReportRampInspection';
static SafetyQMSReportReportRampInspectionDetail='SafetyQMSReportReportRampInspectionDetail';
static SafetyQMSReportReportFindAllFindingYearPieChart='SafetyQMSReportReportFindAllFindingYearPieChart';
static SafetyQMSBasicInfoNotification='SafetyQMSBasicInfoNotification';
static SafetyQMSBasicInfoNotificationChangeState='SafetyQMSBasicInfoNotificationChangeState';
static SafetyQMSBasicInfoNotificationFindByUserId='SafetyQMSBasicInfoNotificationFindByUserId';
static SafetyQMSSchedulerFinding='SafetyQMSSchedulerFinding';
static SafetyQMSSchedulerFindingSave='SafetyQMSSchedulerFindingSave';
static SafetyQMSSchedulerFindingGetByScheduler='SafetyQMSSchedulerFindingGetByScheduler';
static SafetyQMSSchedulerFindingGetBySchedulerForNotification='SafetyQMSSchedulerFindingGetBySchedulerForNotification';
static SafetyQMSSchedulerFindingFind='SafetyQMSSchedulerFindingFind';
static SafetyQMSSchedulerFindingFindAll='SafetyQMSSchedulerFindingFindAll';
static SafetyQMSSchedulerFindingDelete='SafetyQMSSchedulerFindingDelete';
static SafetyQMSSchedulerFindingFindOpenFinding='SafetyQMSSchedulerFindingFindOpenFinding';
static SafetyQMSSchedulerFindingFindLevelTopFinding='SafetyQMSSchedulerFindingFindLevelTopFinding';
static SafetyQMSSchedulerFindingFinalFinding='SafetyQMSSchedulerFindingFinalFinding';
static SafetyQMSSchedulerExternalFinding='SafetyQMSSchedulerExternalFinding';
static SafetyQMSSchedulerExternalFindingSave='SafetyQMSSchedulerExternalFindingSave';
static SafetyQMSSchedulerExternalFindingFindAll='SafetyQMSSchedulerExternalFindingFindAll';
static SafetyQMSSchedulerExternalFindingFind='SafetyQMSSchedulerExternalFindingFind';
static SafetyQMSSchedulerCorrectiveAction='SafetyQMSSchedulerCorrectiveAction';
static SafetyQMSSchedulerCorrectiveActionSave='SafetyQMSSchedulerCorrectiveActionSave';
static SafetyQMSSchedulerAuditorFinding='SafetyQMSSchedulerAuditorFinding';
static SafetyQMSSchedulerAuditorFindingFindAll='SafetyQMSSchedulerAuditorFindingFindAll';
static SafetyQMSSchedulerAuditorFindingSave='SafetyQMSSchedulerAuditorFindingSave';
static SafetyQMSSchedulerAuditeeFinding='SafetyQMSSchedulerAuditeeFinding';
static SafetyQMSSchedulerAuditeeFindingFindAll='SafetyQMSSchedulerAuditeeFindingFindAll';
static SafetyQMSSchedulerAuditeeFindingFind='SafetyQMSSchedulerAuditeeFindingFind';
static SafetyQMSBasicInfoBlob='SafetyQMSBasicInfoBlob';
static SafetyQMSBasicInfoBlobFile='SafetyQMSBasicInfoBlobFile';
static SafetyQMSBasicInfoBlobFindAllBlobs='SafetyQMSBasicInfoBlobFindAllBlobs';
static SafetyQMSBasicInfoBlobDelete='SafetyQMSBasicInfoBlobDelete';
static SafetyQMSBasicInfoBlobFindBlobDescription='SafetyQMSBasicInfoBlobFindBlobDescription';
static SafetyOtherAuditeeDashboard='SafetyOtherAuditeeDashboard';
static SafetyOtherAuditorDashboard='SafetyOtherAuditorDashboard';
//ECTM
  static Ectm='Ectm';



  //crewManagement

  static CrewManagement = 'CrewManagement';
  static CrewManagementCrewScheduler = 'CrewManagementCrewScheduler';
  static CrewManagementCrewSchedulerBrowseCrew = 'CrewManagementCrewSchedulerBrowseCrew';
  static CrewManagementCrewSchedulerTimetable = 'CrewManagementCrewSchedulerTimetable';
  static CrewManagementCrewSchedulerScheduler = 'CrewManagementCrewSchedulerScheduler';
  static CrewManagementCrewSchedulerStatistics = 'CrewManagementCrewSchedulerStatistics';
  static CrewManagementCrewSchedulerReports = 'CrewManagementCrewSchedulerReports';
  static CrewManagementCrewSchedulerBaseInfo = 'CrewManagementCrewSchedulerBaseInfo';
  static CrewManagementBasicInfoFindAll = 'CrewManagementBasicInfoFindAll';
  static SchedulerPlan = 'SchedulerPlan';

///
  static MangeFlight = 'MangeFlight';
  static MangeFlightBasicInfo = 'MangeFlightBasicInfo';
  static MangeFlightBasicInfoManufact = 'MangeFlightBasicInfoManufact';
  static MangeFlightBasicInfoManufactSave = 'MangeFlightBasicInfoManufactSave';
  static Dispatch = "Dispatch";

  //Orders

  static Orders = 'Orders';
  static OrdersQc = 'OrdersQc';
  static OrdersQcInspect = 'OrdersQcInspect';
  static OrdersQcInspectFindAll = 'OrdersQcInspectFindAll';


}
